### ISSUE TITLE
In the Song List, spam clicking the next song in the list can make it stay expanded

### ISSUE THREAD

**Issue by EIRTeam-Cirno** [EIRTeam/Project-Heartbeat#165]
<kbd>[![mikurisu39_](https://cdn.discordapp.com/avatars/464596514510077963/ec1879642b4848788d76f306f84e2d34.webp?size=40)](https://discord.com/channels/640872911678341130/1290199691232809033/1290199691232809033)</kbd> [mikurisu39_](https://discord.com/channels/640872911678341130/1290199691232809033/1290199691232809033)  `BOT`

This is similar to "#150: Unsubscribe button keeps song expanded". Except instead of pressing the unsub button, you spam click the next song and keep advancing the list. Pretty quickly, the expanded songs will start to accumulate.

https://www.youtube.com/watch?v=eQqa2DVnDew

**Comment by EIREXE** [comment]
Should be fixed already in beta iirc.
