### ISSUE TITLE
Editor song doesn't appear when scrolling from left to right, but does appear from right to left

### ISSUE THREAD

**Issue by EIRTeam-Cirno** [EIRTeam/Project-Heartbeat#43]
<kbd>[![mikurisu](https://cdn.discordapp.com/avatars/464596514510077963/0c319478c1938bfcb6f6a8f05cb8a4a3.webp?size=40)](https://discord.com/channels/640872911678341130/1242987433637974060/1242987433637974060)</kbd> [mikurisu](https://discord.com/channels/640872911678341130/1242987433637974060/1242987433637974060)  `BOT`

Editor song doesn't appear when scrolling from left to right, but does appear when changing menus from right to left. 

If I press Down when the song isn't showing, it suddenly appears. 🤔

**Comment by EIREXE** [comment]
Fixed in beta, hopefully, let me know if it did.
