### ISSUE TITLE
slide inputs incorrect in some MM+ charts

### ISSUE THREAD

**Issue by Xerehm** [EIRTeam/Project-Heartbeat#83]
In some MM+ charts, more frequently in modded charts, slides add extra inputs not present in the original game.

here is a visual comparison ("Sister’s ∞ mercY" Ex from the "Project Eden" modpack):
https://youtu.be/D760hH5B0Qg
(the problem is most visible at the very end)

here it is in a vanilla MM+ chart (Intense Voice ExEx):
![image](https://github.com/EIRTeam/Project-Heartbeat/assets/57718861/3fe592e6-d36a-417f-b6ea-2906b840afa7)

**Comment by hiki8man** [comment]
chain slide in dsc is hard to understand how it's work
no one really know how it's works and that's why
for now PHB will only check time value and y positon to let it works in most times but it's will still not works in some chart

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![EIREXE](https://cdn.discordapp.com/avatars/121906432399507456/15624f1859c55f1b1429a0aa5eb4da68.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249094209349091491)</kbd> [EIREXE](https://discord.com/channels/640872911678341130/1249024787603259514/1249094209349091491)  `BOT`

yeah, basically that, its very strange how diva works and i haven't figured it out properly yet, i'll have to ask koren

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![Steven](https://cdn.discordapp.com/avatars/219966809833472010/1dd89592649f192999162b0893ce5384.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249102170876547102)</kbd> [Steven](https://discord.com/channels/640872911678341130/1249024787603259514/1249102170876547102)  `BOT`

I did some poking around in comfy to figure out how slide chains were parsed for my own dsc parsing and as far as I could tell, it seemed like the only thing that mattered was the beat separation. I think comfy uses a cutoff of (20000ms / bpm) as the maximum time separation between notes, which is a beat separation of a 12th.

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![Steven](https://cdn.discordapp.com/avatars/219966809833472010/1dd89592649f192999162b0893ce5384.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249104336672526452)</kbd> [Steven](https://discord.com/channels/640872911678341130/1249024787603259514/1249104336672526452)  `BOT`

Even if comfy doesn't match how diva parses it, idk if it would really matter, since the modded charts are made in comfy anyway and that heuristic should work for all officials.

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![Pascal](https://cdn.discordapp.com/avatars/562499426761965568/f59a958b18909c8c03b3129938c88459.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249104544458080256)</kbd> [Pascal](https://discord.com/channels/640872911678341130/1249024787603259514/1249104544458080256)  `BOT`

Does that mean Comfy can't create sliders faster than twelfths?

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![Steven](https://cdn.discordapp.com/avatars/219966809833472010/1dd89592649f192999162b0893ce5384.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249104883282477167)</kbd> [Steven](https://discord.com/channels/640872911678341130/1249024787603259514/1249104883282477167)  `BOT`

Slower than 12ths.

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![Steven](https://cdn.discordapp.com/avatars/219966809833472010/1dd89592649f192999162b0893ce5384.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249105060617785374)</kbd> [Steven](https://discord.com/channels/640872911678341130/1249024787603259514/1249105060617785374)  `BOT`

*Chains slower than 12ths. Sliders are defined different than slide chains, so it's not applicable to this cutoff.

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![Pascal](https://cdn.discordapp.com/avatars/562499426761965568/f59a958b18909c8c03b3129938c88459.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249105320228159559)</kbd> [Pascal](https://discord.com/channels/640872911678341130/1249024787603259514/1249105320228159559)  `BOT`

Oh, I see.

**Comment by EIRTeam-Cirno** [comment]
<kbd>[![EIREXE](https://cdn.discordapp.com/avatars/121906432399507456/15624f1859c55f1b1429a0aa5eb4da68.webp?size=40)](https://discord.com/channels/640872911678341130/1249024787603259514/1249230777749606433)</kbd> [EIREXE](https://discord.com/channels/640872911678341130/1249024787603259514/1249230777749606433)  `BOT`

Fixed by 0a28c114c2bac66c3e50712fbc8446f03353a402 (let me know if it actually does)
